baseURL = 'https://main--fascinating-malabi-cb95bc.netlify.app/https://fascinating-malabi-cb95bc.netlify.app'
languageCode = 'en'
title = 'Torstein Norendal'



[params]
  contentTypeName = "posts"
  themeColor = "green"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = true

[languages]
  [languages.en]
    title = "Torstein"
    subtitle = "Løsningsarkitekt"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Torstein Norendal: Løsningsarkitekt"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "om"
        name = "Om"
        weight = 1
        url = "/om"
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        weight = 2
        url = "/posts"
